export const apiUrls = {
    posts: '/api/posts',
    tags: '/api/tags',
    notes: '/api/notes',
    noteInteractions: '/api/notes/interactions',
    comments: '/api/comments',
    bookmarks: '/api/bookmarks',
    users: '/api/users',
    docs: '/api-docs',
    static: '/api/static',
    upload: '/api/upload',
    uploadPostImages: '/api/upload-post-images',
    uploadNoteImages: '/api/upload-note-images',
    uploadUserAvatar: '/api/upload-user-avatar',
    deleteCover: '/api/delete-cover/:fileName',
    deletePostImage: '/api/delete-postimage/:fileName',
    deleteNoteImage: '/api/delete-noteimage/:fileName',
    deleteUserAvatar: '/api/delete-useravatar/:fileName',
}